# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cutoff <- function(s_cu, lam_cu) {
    .Call('_softimpute_cutoff', PACKAGE = 'softimpute', s_cu, lam_cu)
}

S_lambda <- function(X_sl, lam_sl) {
    .Call('_softimpute_S_lambda', PACKAGE = 'softimpute', X_sl, lam_sl)
}

P_Ome <- function(X_p, P_O) {
    .Call('_softimpute_P_Ome', PACKAGE = 'softimpute', X_p, P_O)
}

softimpute <- function(X_miss, P_si, lambda) {
    .Call('_softimpute_softimpute', PACKAGE = 'softimpute', X_miss, P_si, lambda)
}

